config/routes.rb
FinDocs::Application.routes.draw do
  resources :documents

  resources :user_logins

end

app/models/document.rb
class Document < ActiveRecord::Base
  
  attr_accessible :AmtInvested, :endDate, :name, :startDate, :userIds
  has_and_belongs_to_many :user_login	
end

app/models/user_login.rb
class UserLogin < ActiveRecord::Base
  attr_accessible :Email, :dateCreated, :name, :password, :documentsIds
  has_and_belongs_to_many :document
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  # GET /documents
  # GET /documents.json
  def index
    @documents = Document.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @documents }
    end
  end

  # GET /documents/1
  # GET /documents/1.json
  def show
    @document = Document.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @document }
    end
  end

  # GET /documents/new
  # GET /documents/new.json
  def new
    @document = Document.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @document }
    end
  end

  # GET /documents/1/edit
  def edit
    @document = Document.find(params[:id])
  end

  # POST /documents
  # POST /documents.json
  def create
    @document = Document.new(params[:document])

    respond_to do |format|
      if @document.save
        format.html { redirect_to @document, notice: 'Document was successfully created.' }
        format.json { render json: @document, status: :created, location: @document }
      else
        format.html { render action: "new" }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /documents/1
  # PUT /documents/1.json
  def update
    @document = Document.find(params[:id])

    respond_to do |format|
      if @document.update_attributes(params[:document])
        format.html { redirect_to @document, notice: 'Document was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1
  # DELETE /documents/1.json
  def destroy
    @document = Document.find(params[:id])
    @document.destroy

    respond_to do |format|
      format.html { redirect_to documents_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/user_logins_controller.rb
class UserLoginsController < ApplicationController
  # GET /user_logins
  # GET /user_logins.json
  def index
    @user_logins = UserLogin.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @user_logins }
    end
  end

  # GET /user_logins/1
  # GET /user_logins/1.json
  def show
    @user_login = UserLogin.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user_login }
    end
  end

  # GET /user_logins/new
  # GET /user_logins/new.json
  def new
    @user_login = UserLogin.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user_login }
    end
  end

  # GET /user_logins/1/edit
  def edit
    @user_login = UserLogin.find(params[:id])
  end

  # POST /user_logins
  # POST /user_logins.json
  def create
    @user_login = UserLogin.new(params[:user_login])

    respond_to do |format|
      if @user_login.save
        format.html { redirect_to @user_login, notice: 'User login was successfully created.' }
        format.json { render json: @user_login, status: :created, location: @user_login }
      else
        format.html { render action: "new" }
        format.json { render json: @user_login.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /user_logins/1
  # PUT /user_logins/1.json
  def update
    @user_login = UserLogin.find(params[:id])

    respond_to do |format|
      if @user_login.update_attributes(params[:user_login])
        format.html { redirect_to @user_login, notice: 'User login was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user_login.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_logins/1
  # DELETE /user_logins/1.json
  def destroy
    @user_login = UserLogin.find(params[:id])
    @user_login.destroy

    respond_to do |format|
      format.html { redirect_to user_logins_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/user_logins_helper.rb
module UserLoginsHelper
end

app/views/documents/_form.html.erb
<%= form_for(@document) do |f| %>
  <% if @document.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@document.errors.count, "error") %> prohibited this document from being saved:</h2>

      <ul>
      <% @document.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Fund Name" %><br />
    <%= f.text_field :name  %>
  </div>
  <div class="field">
    <%= f.label "Start Date" %><br />
    <%= f.date_select :startDate  %>
  </div>
  <div class="field">
    <%= f.label "End Date" %><br />
    <%= f.date_select :endDate  %>
  </div>
  <div class="field">
    <%= f.label "Amount Invested" %><br />
    <%= f.text_field :AmtInvested  %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/documents/edit.html.erb
<h1>Editing document</h1>

<%= render 'form' %>

<%= link_to 'Show', @document %> |
<%= link_to 'Back', documents_path %>

app/views/documents/index.html.erb
<h1>Listing documents</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Start Date</th>
    <th>End Date</th>
    <th>Amount Invested</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @documents.each do |document| %>
  <tr>
    <td><%= document.name %></td>
    <td><%= document.startDate %></td>
    <td><%= document.endDate %></td>
    <td><%= document.AmtInvested %></td>
    <td><%= link_to 'Show', document %></td>
    <td><%= link_to 'Edit', edit_document_path(document) %></td>
    <td><%= link_to 'Destroy', document, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Document', new_document_path %>

app/views/documents/new.html.erb
<h1>New document</h1>

<%= render 'form' %>

<%= link_to 'Back', documents_path %>

app/views/documents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @document.name %>
</p>

<p>
  <b>Start Date:</b>
  <%= @document.startDate %>
</p>

<p>
  <b>End Date:</b>
  <%= @document.endDate %>
</p>

<p>
  <b>Amount Invested:</b>
  <%= @document.AmtInvested %>
</p>


<%= link_to 'Edit', edit_document_path(@document) %> |
<%= link_to 'Back', documents_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FinDocs</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <link rel="stylesheet" href="http://netdna.bootstrapcdn.com/twitter-bootstrap/2.3.1/css/bootstrap-combined.min.css"> 
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
 <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="brand" href="#">FinDocs</a>
          <div class="nav-collapse collapse">
            <ul class="nav">
              <li class="active"><a href="#">Home</a></li>
              <li><a href="#about">About</a></li>
              <li><a href="#contact">Contact</a></li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><a href="#">Action</a></li>
                  <li><a href="#">Another action</a></li>
                  <li><a href="#">Something else here</a></li>
                  <li class="divider"></li>
                  <li class="nav-header">Nav header</li>
                  <li><a href="#">Separated link</a></li>
                  <li><a href="#">One more separated link</a></li>
                </ul>
              </li>
            </ul>
            <form class="navbar-form pull-right">
              <input class="span2" type="text" placeholder="Email">
              <input class="span2" type="password" placeholder="Password">
              <button type="submit" class="btn">Sign in</button>
            </form>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>
<div class = "container">
<%= yield %>
</div>
</body>
</html>

app/views/user_logins/_form.html.erb
<%= form_for(@user_login) do |f| %>
  <% if @user_login.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_login.errors.count, "error") %> prohibited this user_login from being saved:</h2>

      <ul>
      <% @user_login.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Username %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :Password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :Email %><br />
    <%= f.email_field :Email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_logins/edit.html.erb
<h1>Editing user_login</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_login %> |
<%= link_to 'Back', user_logins_path %>

app/views/user_logins/index.html.erb
<h1>Listing user_logins</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Password</th>
    <th>Date Created</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @user_logins.each do |user_login| %>
  <tr>
    <td><%= user_login.name %></td>
    <td><%= user_login.password %></td>
    <td><%= user_login.dateCreated %></td>
    <td><%= user_login.Email %></td>
    <td><%= link_to 'Show', user_login %></td>
    <td><%= link_to 'Edit', edit_user_login_path(user_login) %></td>
    <td><%= link_to 'Destroy', user_login, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User login', new_user_login_path %>

app/views/user_logins/new.html.erb
<h1>New user_login</h1>

<%= render 'form' %>

<%= link_to 'Back', user_logins_path %>

app/views/user_logins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Userid:</b>
  <%= @user_login.userId %>
</p>

<p>
  <b>Name:</b>
  <%= @user_login.name %>
</p>

<p>
  <b>Password:</b>
  <%= @user_login.password %>
</p>

<p>
  <b>Datecreated:</b>
  <%= @user_login.dateCreated %>
</p>

<p>
  <b>Email:</b>
  <%= @user_login.Email %>
</p>


<%= link_to 'Edit', edit_user_login_path(@user_login) %> |
<%= link_to 'Back', user_logins_path %>